<a href="https://colab.research.google.com/github/yasinsoylu1997/NLP-PROJELER-TOPLU/blob/main/nlp_sklearn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf

In [2]:
products= pd.read_csv('sample.csv')

In [3]:
products

yildizSayisi  ... yorumLike
0                 1  ...         0
1                 1  ...         7
2                 1  ...         2
3                 1  ...         1
4                 1  ...         2
...             ...  ...       ...
49995             5  ...         0
49996             5  ...         0
49997             5  ...         0
49998             5  ...         0
49999             5  ...         0

[50000 rows x 3 columns]

In [4]:
len(products) - len(products.dropna())


0

In [5]:
len(products)


50000

In [6]:
products = products.dropna()


In [7]:
for i in range(0,len(products)-1):
    if type(products.iloc[i]['yorum']) != str:
        products.iloc[i]['yorum'] = str(products.iloc[i]['yorum'])

In [8]:
products = products[products['yildizSayisi'] != 3]


In [9]:
def sentiment(n):
    return 1 if n >= 4 else 0
products['sentiment'] = products['yildizSayisi'].apply(sentiment)
products.head()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until


yildizSayisi  ... sentiment
0             1  ...         0
1             1  ...         0
2             1  ...         0
3             1  ...         0
4             1  ...         0

[5 rows x 4 columns]

In [10]:
X = products['yorum']
y = products['sentiment']

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

In [12]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
ctmTr = cv.fit_transform(X_train)
X_test_dtm = cv.transform(X_test)

In [13]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
model = LogisticRegression()
model.fit(ctmTr, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


LogisticRegression()

In [14]:
y_pred_class = model.predict(X_test_dtm)
y_pred_class

array([0, 0, 0, ..., 0, 1, 0])

In [15]:
accuracy_score(y_test, y_pred_class)


0.8893

In [16]:
from sklearn import metrics
print(metrics.classification_report(y_test, y_pred_class))

              precision    recall  f1-score   support

           0       0.89      0.89      0.89      5014
           1       0.89      0.89      0.89      4986

    accuracy                           0.89     10000
   macro avg       0.89      0.89      0.89     10000
weighted avg       0.89      0.89      0.89     10000



In [17]:
from sklearn.naive_bayes import MultinomialNB
model2=MultinomialNB()
model2.fit(ctmTr, y_train)

MultinomialNB()

In [18]:
y_pred2_class = model2.predict(X_test_dtm)
y_pred2_class

array([0, 0, 0, ..., 0, 1, 1])

In [19]:
accuracy_score(y_test, y_pred2_class)


0.8826

In [20]:
from sklearn import metrics
print(metrics.classification_report(y_test, y_pred2_class))

              precision    recall  f1-score   support

           0       0.90      0.86      0.88      5014
           1       0.86      0.91      0.89      4986

    accuracy                           0.88     10000
   macro avg       0.88      0.88      0.88     10000
weighted avg       0.88      0.88      0.88     10000



In [21]:
from sklearn.linear_model import SGDClassifier
model3=SGDClassifier()
model3.fit(ctmTr, y_train)

SGDClassifier()

In [22]:
y_pred3_class = model3.predict(X_test_dtm)
y_pred3_class

array([0, 0, 0, ..., 0, 1, 0])

In [23]:
accuracy_score(y_test, y_pred3_class)


0.8876

In [24]:
from sklearn import metrics
print(metrics.classification_report(y_test, y_pred3_class))

              precision    recall  f1-score   support

           0       0.89      0.88      0.89      5014
           1       0.88      0.89      0.89      4986

    accuracy                           0.89     10000
   macro avg       0.89      0.89      0.89     10000
weighted avg       0.89      0.89      0.89     10000



In [25]:
from sklearn.linear_model import LogisticRegression
model4=LogisticRegression()
model4.fit(ctmTr, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


LogisticRegression()

In [26]:
y_pred4_class = model4.predict(X_test_dtm)
y_pred4_class

array([0, 0, 0, ..., 0, 1, 0])

In [27]:
accuracy_score(y_test, y_pred4_class)


0.8893